{% set name = "awswrangler" %}
{% set version = "2.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e666edf22a7db25453f93191903137833bc9df3eff4cf2ecdf6b450c5a55a3db

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7.1,<3.11
    - poetry-core >=1.0.0
    - pip
  run:
    - boto3 >=1.20.17,<2.0.0
    - botocore >=1.23.17,<2.0.0
    - jsonpath-ng >=1.5.3,<2.0.0
    - numpy >=1.21.0,<2.0.0
    - openpyxl >=3.0.0,<3.1.0
    - opensearch-py >=1.0.0,<2.0.0
    - pandas >=1.2.0,<2.0.0
    - pg8000 >=1.20.0,<2.0.0
    - progressbar2 >=3.53.3,<4.0.0
    - pyarrow >=2.0.0,<7.1.0
    - pymysql >=1.0.0,<2.0.0
    - python >=3.6.2,<3.11
    - redshift_connector >=2.0.889,<2.1.0
    - requests-aws4auth >=1.1.1,<2.0.0
    - gremlinpython >=3.5.2,<4.0.0
    - backoff >=1.11.1,<2.0.0
    - sparqlwrapper >=1.8.5,<2.0.0
    - rdflib >=4.0,<7.0.0
  run_constrained:
    - pyodbc >=4.0.32,=4.0

test:
  imports:
    - awswrangler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws-data-wrangler.readthedocs.io/
  summary: Pandas on AWS
  description: |
    An open-source Python package that extends the power of Pandas library to AWS connecting DataFrames
    and AWS data related services. Easy integration with Athena, Redshift, Glue, Timestream, Neptune,
    OpenSearch, QuickSight, Chime, CloudWatchLogs, DynamoDB, EMR, SecretManager, PostgreSQL, MySQL, SQLServer
    and S3 (Parquet, CSV, JSON and EXCEL).

    Built on top of other open-source projects like Pandas, Apache Arrow and Boto3,
    it offers abstracted functions to execute usual ETL tasks like load/unload
    data from Data Lakes, Data Warehouses and Databases.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.txt
    - NOTICE.txt
    - THIRD_PARTY.txt
  dev_url: https://github.com/awslabs/aws-data-wrangler
  doc_url: https://aws-data-wrangler.readthedocs.io/

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - igorborgest
    - jaidisido
    - kukushking
    - BastianZim
