{% set name = "awswrangler" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73f3d5bef31d5446cf7cd4a1f127d82c2c1688931e4f66ca4514af4b83ae6e14


build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6,<3.9
    - pip
  run:
    - python >=3.6,<3.9
    - numpy ~=1.18.0
    - pandas ~=1.0.0
    - pyarrow ~=0.16.0
    - boto3 >=1.12.22
    - botocore >=1.15.22
    - s3fs ~=0.4.0
    - psycopg2-binary ~=2.8.0
    - pymysql ~=0.9.0
    - SQLAlchemy ==1.3.13
    - sqlalchemy-redshift ~=0.7.0

test:
  imports:
    - awswrangler

about:
  home: https://github.com/awslabs/aws-data-wrangler
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Pandas on AWS'
  description: |
    An open-source Python package that extends the power of Pandas library to AWS connecting DataFrames
    and AWS data related services (Amazon Redshift, AWS Glue, Amazon Athena, Amazon EMR, etc).
    Built on top of other open-source projects like Pandas, Apache Arrow, Boto3, s3fs, SQLAlchemy,
    Psycopg2 and PyMySQL, it offers abstracted functions to execute usual ETL tasks like load/unload
    data from Data Lakes, Data Warehouses and Databases.
  doc_url: https://aws-data-wrangler.readthedocs.io

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - igorborgest
