{% set name = "awswrangler" %}
{% set version = "0.0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a5b27325dbe3d7e7f744cbc07a823ee6dd7e9f54953da8c20eeefe1fdad8821

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.17.3
    - pandas >=0.25.3
    - pyarrow >=0.15.1
    - botocore >=1.13.18
    - boto3 >=1.1.18
    - s3fs >=0.4.0
    - tenacity >=6.0.0
    - pg8000 >=1.13.2

test:
  imports:
    - awswrangler

about:
  home: https://github.com/awslabs/aws-data-wrangler
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Utility belt to handle data on AWS'
  description: 'Utility belt to handle data on AWS'
  doc_url: https://aws-data-wrangler.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
