{% set name = "awswrangler" %}
{% set version = "2.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 764a2c153230b8f6722a01d541b7340f32b6e52f1940a29a8d106f00ffab7f67
  patches:
    - 0001-Make-compatible.patch

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7.1,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7.1,<4.0
    - backoff >=1.11.1,<3.0.0
    - boto3 >=1.24.11,<2.0.0
    - botocore >=1.27.11,<2.0.0
    - gremlinpython >=3.5.2,<4.0.0
    - jsonpath-ng >=1.5.3,<2.0.0
    - openpyxl >=3.0.0,<3.1.0
    - opensearch-py >=1,<3
    - pandas >=1.2.0,<=1.5.1,!=1.5.0
    - pg8000 >=1.20.0,<2.0.0
    - progressbar2 >=4.0.0,<5.0.0
    - pyarrow >=2.0.0,<10.1.0
    - pymysql >=1.0.0,<2.0.0
    - redshift_connector >=2.0.889,<2.1.0
    - requests-aws4auth >=1.1.1,<2.0.0
    - numpy >=1.21.0,<2.0.0
  run_constrained:
    - pyodbc >=4.0.32,=4.0
    - sparqlwrapper >=1.8.5,<3.0.0
    - rdflib >=6.0.0,=6.0
    - oracledb >=1.0.0,=1.0

test:
  imports:
    - awswrangler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws-sdk-pandas.readthedocs.io
  summary: Pandas on AWS
  description: |
    An open-source Python package that extends the power of Pandas library to AWS connecting DataFrames
    and AWS data related services. Easy integration with Athena, Redshift, Glue, Timestream, Neptune,
    OpenSearch, QuickSight, Chime, CloudWatchLogs, DynamoDB, EMR, SecretManager, PostgreSQL, MySQL, SQLServer
    and S3 (Parquet, CSV, JSON and EXCEL).

    Built on top of other open-source projects like Pandas, Apache Arrow and Boto3,
    it offers abstracted functions to execute usual ETL tasks like load/unload
    data from Data Lakes, Data Warehouses and Databases.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.txt
    - NOTICE.txt
    - THIRD_PARTY.txt
  dev_url: https://github.com/aws/aws-sdk-pandas
  doc_url: https://aws-sdk-pandas.readthedocs.io

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - igorborgest
    - jaidisido
    - kukushking
    - BastianZim
    - malachi-constant
    - cnfait
    - LeonLuttenberger
