{% set name = "awswrangler" %}
{% set version = "3.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aef0eb4aadb54bfaf1a26cbed915b10cf4682fb97979e02f23ff560453db44f4

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - uv
    - pip
    - hatchling
  run:
    - geopandas >=0.13.2,<0.14.0
    - typing_extensions >=4.4.0,<5
    - python >={{ python_min }},<4.0
    - boto3 >=1.20.32,<2
    - botocore >=1.23.32,<2
    - pandas >=1.2.0,<3.0.0
    - numpy >=1.26,<3.0
    - pyarrow >=18.0.0,<21.0.0
    - typing-extensions >=4.4.0,<5.0.0
    - packaging >=21.1,<26.0
    - setuptools
  run_constrained:
    # Databases
    - redshift_connector >=2.0.0,<3.0.0
    - pymysql >=1.0.0,<2.0.0
    - pg8000 >=1.29.0,<2.0.0
    - pyodbc >=4.0.0,<6.0.0
    - oracledb >=1.0.0,<3.0.0
    # Graph
    - gremlinpython >=3.7.1,<4.0.0
    - sparqlwrapper >=2.0.0,<3.0.0
    - requests >=2.0.0,<3.0.0
    - aiohttp >=3.9.0,<4.0.0
    - async-timeout >=4.0.3,<6.0.0
    # OpenSearch
    - opensearch-py >=2,<4
    - requests-aws4auth >=1.1.1,<2.0.0
    - jsonpath-ng >=1.5.3,<2.0.0
    # Other
    - openpyxl >=3.0.0,<4.0.0
    - progressbar2 >=4.0.0,<5.0.0
    - rdflib >=6.0.0,=6.0
    - deltalake >=0.18.0,<0.26.0
    - geopandas >=1.0.0,<2
    # Distributed
    - modin >=0.31,<0.3
    - ray >=2.49.0,<3


test:
  imports:
    - awswrangler
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws-sdk-pandas.readthedocs.io
  summary: Pandas on AWS
  description: |
    An open-source Python package that extends the power of Pandas library to AWS connecting DataFrames
    and AWS data related services. Easy integration with Athena, Redshift, Glue, Timestream, Neptune,
    OpenSearch, QuickSight, Chime, CloudWatchLogs, DynamoDB, EMR, SecretManager, PostgreSQL, MySQL, SQLServer
    and S3 (Parquet, CSV, JSON and EXCEL).

    Built on top of other open-source projects like Pandas, Apache Arrow and Boto3,
    it offers abstracted functions to execute usual ETL tasks like load/unload
    data from Data Lakes, Data Warehouses and Databases.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.txt
    - NOTICE.txt
    - THIRD_PARTY.txt
  dev_url: https://github.com/aws/aws-sdk-pandas
  doc_url: https://aws-sdk-pandas.readthedocs.io

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - igorborgest
    - jaidisido
    - kukushking
    - BastianZim
    - EthanBunce
