{% set name = "awswrangler" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be3275c323ff44aa16286c0cfc17edd64adbb2fb95a35bc17eb21e5c543201f4


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<3.9
    - pip
  run:
    - python >=3.6,<3.9
    - boto3 >=1.12.49,<2.0.0
    - botocore >=1.15.49,<2.0.0
    - numpy >=1.18.0,<1.21.0
    - pandas >=1.1.0,<1.3.0
    - pyarrow >=2.0.0,<3.1.0
    - redshift_connector ~=2.0.0
    - pymysql >=0.9.0,<1.1.0
    - pg8000 >=1.16.0,<1.19.0
    - openpyxl

test:
  imports:
    - awswrangler

about:
  home: https://github.com/awslabs/aws-data-wrangler
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Pandas on AWS
  description: |
    An open-source Python package that extends the power of Pandas library to AWS connecting DataFrames
    and AWS data related services. Easy integration with Athena, Redshift, Glue, Timestream, QuickSight,
    Chime, CloudWatchLogs, DynamoDB, EMR, SecretManager, PostgreSQL, MySQL, SQLServer and 
    S3 (Parquet, CSV, JSON and EXCEL).
    Built on top of other open-source projects like Pandas, Apache Arrow and Boto3, 
    it offers abstracted functions to execute usual ETL tasks like load/unload
    data from Data Lakes, Data Warehouses and Databases.
  doc_url: https://aws-data-wrangler.readthedocs.io

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - igorborgest
    - jaidisido
