{% set name = "awswrangler" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ca20be9dfcee56e7d13d1287874fe2c8a3a7b0cd5063f62c6253816413f7487

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - boto3 >=1.20.32,<2.0.0
    - botocore >=1.23.32,<2.0.0
    - pandas >=1.2.0,<3.0.0
    - numpy >=1.18.0,<2.0.0
    - pyarrow >=7.0.0
    - typing-extensions >=4.4.0,<5.0.0
    - packaging >=21.1,<24.0
  run_constrained:
    # Databases
    - redshift_connector >=2.0.0,<3.0.0
    - pymysql >=1.0.0,<2.0.0
    - pg8000 >=1.29.0,<2.0.0
    - pyodbc >=4.0.0,<6.0.0
    - oracledb >=1.0.0,<3.0.0
    # Graph
    - gremlinpython >=3.7.1,<4.0.0
    - sparqlwrapper >=2.0.0,<3.0.0
    # OpenSearch
    - opensearch-py >=2,<3
    - requests-aws4auth >=1.1.1,<2.0.0
    - jsonpath-ng >=1.5.3,<2.0.0
    # Other
    - openpyxl >=3.0.0,<4.0.0
    - progressbar2 >=4.0.0,<5.0.0
    - rdflib >=6.0.0,=6.0
    - deltalake >=0.6.4,<0.16.0
    # Distributed
    - modin >=0.23.1post0,<1.0.0
    - ray[default,data] >=2.9.0,<3.0.0


test:
  imports:
    - awswrangler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws-sdk-pandas.readthedocs.io
  summary: Pandas on AWS
  description: |
    An open-source Python package that extends the power of Pandas library to AWS connecting DataFrames
    and AWS data related services. Easy integration with Athena, Redshift, Glue, Timestream, Neptune,
    OpenSearch, QuickSight, Chime, CloudWatchLogs, DynamoDB, EMR, SecretManager, PostgreSQL, MySQL, SQLServer
    and S3 (Parquet, CSV, JSON and EXCEL).

    Built on top of other open-source projects like Pandas, Apache Arrow and Boto3,
    it offers abstracted functions to execute usual ETL tasks like load/unload
    data from Data Lakes, Data Warehouses and Databases.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.txt
    - NOTICE.txt
    - THIRD_PARTY.txt
  dev_url: https://github.com/aws/aws-sdk-pandas
  doc_url: https://aws-sdk-pandas.readthedocs.io

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - igorborgest
    - jaidisido
    - kukushking
    - BastianZim
    - malachi-constant
    - cnfait
    - LeonLuttenberger
