{% set name = "awswrangler" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2a89f15a63e13417487588447e61a3a17e375af0ce57c38e9e7822cffcac55b5


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<3.9
    - pip
  run:
    - python >=3.6,<3.9
    - packaging
    - boto3 >=1.12.49,<2.0.0
    - botocore >=1.15.49,<2.0.0
    - numpy >=1.18.0,<1.20.0
    - pymysql >=0.9.0,<0.11.0
    - sqlalchemy-redshift >=0.7.0,<0.9.0
    - pandas >=1.0.0,<1.2.0
    - SQLAlchemy ~=1.3.10
    - pyarrow ~=1.0.0
    - psycopg2 ~=2.8.0

test:
  imports:
    - awswrangler

about:
  home: https://github.com/awslabs/aws-data-wrangler
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Pandas on AWS
  description: |
    An open-source Python package that extends the power of Pandas library to AWS connecting DataFrames
    and AWS data related services (Amazon Redshift, AWS Glue, Amazon Athena, Amazon EMR, Amazon QuickSight, etc).
    Built on top of other open-source projects like Pandas, Apache Arrow, Boto3, SQLAlchemy,
    Psycopg2 and PyMySQL, it offers abstracted functions to execute usual ETL tasks like load/unload
    data from Data Lakes, Data Warehouses and Databases.
  doc_url: https://aws-data-wrangler.readthedocs.io

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
    - igorborgest
