{% set name = "awswrangler" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3bb3eec2d838cfd0f53d436784aca9140d9f6d40bfbf3444736e244a6cf51d22

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.17.2
    - pandas >=0.25.1
    - pyarrow >=0.14.0
    - botocore >=1.12.239
    - boto3 >=1.9.239
    - s3fs >=0.3.4
    - tenacity >=5.1.1
    - pg8000 >=1.13.2

test:
  imports:
    - awswrangler

about:
  home: https://github.com/awslabs/aws-data-wrangler
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Utility belt to handle data on AWS'
  description: 'Utility belt to handle data on AWS'
  doc_url: https://aws-data-wrangler.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
